softusbduino: SoftUsb Class Reference
SoftUsb Class Reference
#include <SoftUsb.h>
Public Member Functions
SoftUsb ()
void begin ()
void refresh ()
Detailed Description
Definition at line 350 of file SoftUsb.h.
Constructor & Destructor Documentation
SoftUsb::SoftUsb () inline
Definition at line 355 of file SoftUsb.h.
References pUsbFunctionSetup, and SoftUsb_UsbFunctionSetup().
    {
        pUsbFunctionSetup = &SoftUsb_UsbFunctionSetup;
    }
Member Function Documentation
void SoftUsb::begin () inline
Definition at line 360 of file SoftUsb.h.
References usbInit(), and usbReconnect().
    {
        // disable timer 0 overflow interrupt (used for millis)
        // TODO: make this portable
        // disable Timer0
        // millis() and delay()
#if defined(TIMSK0)
        TIMSK0 &= !(1 << TOIE0);
#elif defined(TIMSK)
        TIMSK &= !(1 << TOIE0);
#endif
        cli();
        //        wdt_reset();
        //wdt_enable (WDTO_1S);
        wdt_disable();
        /* Even if you don't use the watchdog, turn it off here. On newer devices,
         * the status of the watchdog (on/off, period) is PRESERVED OVER RESET!
         */
        /* RESET status: all port bits are inputs without pull-up.
         * That's the way we need D+ and D-. Therefore we don't need any
         * additional hardware initialization.
         */
        usbInit();
        usbReconnect();
        //      wdt_disable();
        sei();
    }
void SoftUsb::refresh () inline
Definition at line 398 of file SoftUsb.h.
References params::bytes, params::cmd, delay_test(), FreqCount, g_count, g_wdt_auto_reset, FreqCountClass::read1(), return_bool(), return_int8(), run_slow, slow_return, uchar, usbDeviceConnect, usbDeviceDisconnect, usbPoll(), usbReconnect(), and params::word1.
    {
        if (g_wdt_auto_reset)
            wdt_reset();
        if (run_slow)
        {
            wdt_reset();
            run_slow = false;
            usbPoll();
            uchar i = 10; // ms
            while (--i)
            {
                _delay_ms(1);
                usbPoll();
            }
            switch (slow_params.cmd)
            {
#ifdef OneWire_h
            case 65:
            {
                uint8_t ok = one_wire_bus_list[slow_params.bytes[0]]->search(
                        one_wire_address);
                slow_return = return_bool(ok);
            }
            case 66:
            slow_return = return_bool(
                    one_wire_bus_list[slow_params.bytes[0]]->reset());
            break;
            case 67:
            one_wire_bus_list[slow_params.bytes[0]]->select(
                    one_wire_address);
            break;
            case 68:
            one_wire_bus_list[slow_params.bytes[0]]->write(
                    slow_params.bytes[1], slow_params.bytes[2]);
            break;
            case 73:
            slow_return = return_int8(
                    one_wire_bus_list[slow_params.bytes[0]]->read());
            break;
#endif
            case 80:
                cli();
                usbReconnect();
                sei();
                break;
            case 90:
            {
                bool b_usb_disconnect = slow_params.bytes[0];
                if (b_usb_disconnect)
                    usbDeviceDisconnect();
//                USB_INTR_ENABLE &= ~_BV(USB_INTR_ENABLE_BIT);
                gate_length =slow_params.word1;
                startTCCR2B=slow_params.bytes[1];
                g_count = FreqCount.read1();
//                USB_INTR_ENABLE |= _BV(USB_INTR_ENABLE_BIT);
                if (b_usb_disconnect)
                    usbDeviceConnect();
            }
                break;
            case 211:
                slow_return = return_int8(delay_test(&slow_params));
                break;
            }
            wdt_reset();
        }
        usbPoll();
    }
The documentation for this class was generated from the following file:
SoftUsb/SoftUsb.h