softusbduino: FreqCountClass Class Reference
FreqCountClass Class Reference
#include <SoftUsb_timer.h>
Public Member Functions
void begin ()
uint8_t available (void)
uint32_t read (void)
uint32_t read1 ()
Detailed Description
Definition at line 179 of file SoftUsb_timer.h.
Member Function Documentation
uint8_t FreqCountClass::available (void) inline
Definition at line 201 of file SoftUsb_timer.h.
Referenced by read1().
    {
        return count_ready;
    }
void FreqCountClass::begin () inline
Definition at line 182 of file SoftUsb_timer.h.
Referenced by read1().
    {
//        if (msec < 10)
//            return;
        gate_index = 0;
        count_msw = 0;
        count_prev = 0;
        count_ready = 0;
        //counter_init();
        //gate_length = timer_init(msec);
        uint8_t status = SREG;
        cli();
        timer_start();
        timer_isr_latency_delay();
        counter_start();
        SREG = status;
    }
uint32_t FreqCountClass::read (void) inline
Definition at line 206 of file SoftUsb_timer.h.
Referenced by read1().
    {
        uint32_t count;
        uint8_t status;
        status = SREG;
        cli();
        count = count_output;
        count_ready = 0;
        SREG = status;
        return count;
    }
uint32_t FreqCountClass::read1 () inline
Definition at line 224 of file SoftUsb_timer.h.
References available(), begin(), and read().
Referenced by SoftUsb::refresh().
    {
        begin();
        while (!available())
        {
        }
        uint32_t count = read();
        //end();
        return count;
    }
The documentation for this class was generated from the following file:
SoftUsb/SoftUsb_timer.h