softusbduino: SoftUsb/SoftUsb.cpp File Reference
SoftUsb/SoftUsb.cpp File Reference
#include <avr/version.h>
#include <avr/wdt.h>
#include <avr/interrupt.h>
#include <util/delay.h>
#include <avr/pgmspace.h>
#include "usbdrv.h"
#include "generated_version.h"
#include "WProgram.h"
#include "SoftUsb.h"
#include "UsbMain.h"
#include "generated_mcu.h"
#include "pins_arduino.h"
#include "generated_registers.h"
#include "generated_intdefs.h"
Defines
#define MAGIC_NUMBER 42
#define _STR(s) #s
#define STR(s) _STR(s)
#define PA 1
#define PB 2
#define PC 3
#define PD 4
#define PE 5
#define PF 6
#define PG 7
#define PH 8
#define PJ 10
#define PK 11
#define PL 12
#define REGISTER_CHECK 1
#define REGISTER_READ 2
#define REGISTER_WRITE 3
#define REGISTER_ADDRESS 4
#define REGISTER_MISSING 111
#define REGISTER_OK 222
#define BUFFER_SIZE 20
#define TYPE_INT8 1
#define TYPE_INT16 2
#define TYPE_INT32 3
#define TYPE_STRING 4
#define TYPE_FLOAT 5
#define TYPE_VOID 6
#define DEFINE(x) (prog_uint16_t)(&x),
#define MISSING(x)
#define DEFINE(x) __COUNTER__,
#define MISSING(x) (0*__COUNTER__)+
#define DEFINE(x) x,
Functions
usbMsgLen_t return_string (const char *s)
usbMsgLen_t return_int8 (int8_t x)
usbMsgLen_t return_int16 (int16_t x)
usbMsgLen_t return_int32 (int32_t x)
usbMsgLen_t SoftUsb_UsbFunctionSetup (uchar data[8])
Variables
const prog_uint16_t reg_list[] PROGMEM
Define Documentation
#define _STR (s) #s
Definition at line 22 of file SoftUsb.cpp.
#define BUFFER_SIZE 20
Definition at line 44 of file SoftUsb.cpp.
#define DEFINE (x) x,
Definition at line 105 of file SoftUsb.cpp.
#define DEFINE (x) (prog_uint16_t)(&x),
Definition at line 105 of file SoftUsb.cpp.
#define DEFINE (x) __COUNTER__,
Definition at line 105 of file SoftUsb.cpp.
#define MAGIC_NUMBER 42
Definition at line 20 of file SoftUsb.cpp.
Referenced by SoftUsb_UsbFunctionSetup().
#define MISSING (x) (0*__COUNTER__)+
Definition at line 96 of file SoftUsb.cpp.
#define MISSING (x)
Definition at line 96 of file SoftUsb.cpp.
#define PA 1
Definition at line 25 of file SoftUsb.cpp.
#define PB 2
Definition at line 26 of file SoftUsb.cpp.
#define PC 3
Definition at line 27 of file SoftUsb.cpp.
#define PD 4
Definition at line 28 of file SoftUsb.cpp.
#define PE 5
Definition at line 29 of file SoftUsb.cpp.
#define PF 6
Definition at line 30 of file SoftUsb.cpp.
#define PG 7
Definition at line 31 of file SoftUsb.cpp.
#define PH 8
Definition at line 32 of file SoftUsb.cpp.
#define PJ 10
Definition at line 33 of file SoftUsb.cpp.
#define PK 11
Definition at line 34 of file SoftUsb.cpp.
#define PL 12
Definition at line 35 of file SoftUsb.cpp.
#define REGISTER_ADDRESS 4
Definition at line 40 of file SoftUsb.cpp.
Referenced by SoftUsb_UsbFunctionSetup().
#define REGISTER_CHECK 1
Definition at line 37 of file SoftUsb.cpp.
Referenced by SoftUsb_UsbFunctionSetup().
#define REGISTER_MISSING 111
Definition at line 41 of file SoftUsb.cpp.
Referenced by SoftUsb_UsbFunctionSetup().
#define REGISTER_OK 222
Definition at line 42 of file SoftUsb.cpp.
Referenced by SoftUsb_UsbFunctionSetup().
#define REGISTER_READ 2
Definition at line 38 of file SoftUsb.cpp.
Referenced by SoftUsb_UsbFunctionSetup().
#define REGISTER_WRITE 3
Definition at line 39 of file SoftUsb.cpp.
Referenced by SoftUsb_UsbFunctionSetup().
#define STR (s) _STR(s)
Definition at line 23 of file SoftUsb.cpp.
Referenced by SoftUsb_UsbFunctionSetup().
#define TYPE_FLOAT 5
Definition at line 50 of file SoftUsb.cpp.
#define TYPE_INT16 2
Definition at line 47 of file SoftUsb.cpp.
Referenced by return_int16().
#define TYPE_INT32 3
Definition at line 48 of file SoftUsb.cpp.
Referenced by return_int32().
#define TYPE_INT8 1
Definition at line 46 of file SoftUsb.cpp.
Referenced by return_int8().
#define TYPE_STRING 4
Definition at line 49 of file SoftUsb.cpp.
Referenced by return_string().
#define TYPE_VOID 6
Definition at line 51 of file SoftUsb.cpp.
Function Documentation
usbMsgLen_t return_int16 (int16_t x)
Definition at line 68 of file SoftUsb.cpp.
References TYPE_INT16.
Referenced by SoftUsb_UsbFunctionSetup().
{
    dataBuffer[0] = TYPE_INT16;
    dataBuffer[1] = x >> (0 * 8);
    dataBuffer[2] = x >> (1 * 8);
    return 3;
}
usbMsgLen_t return_int32 (int32_t x)
Definition at line 76 of file SoftUsb.cpp.
References TYPE_INT32.
Referenced by SoftUsb_UsbFunctionSetup().
{
    dataBuffer[0] = TYPE_INT32;
    dataBuffer[1] = x >> (0 * 8);
    dataBuffer[2] = x >> (1 * 8);
    dataBuffer[3] = x >> (2 * 8);
    dataBuffer[4] = x >> (3 * 8);
    return 5;
}
usbMsgLen_t return_int8 (int8_t x)
Definition at line 61 of file SoftUsb.cpp.
References TYPE_INT8.
Referenced by SoftUsb_UsbFunctionSetup().
{
    dataBuffer[0] = TYPE_INT8;
    dataBuffer[1] = x;
    return 2;
}
usbMsgLen_t return_string (const char * s)
Definition at line 54 of file SoftUsb.cpp.
References TYPE_STRING.
Referenced by SoftUsb_UsbFunctionSetup().
{
    dataBuffer[0] = TYPE_STRING;
    strcpy((char*) &dataBuffer[1], s);
    return strlen((char*) dataBuffer)+1;
}
usbMsgLen_t SoftUsb_UsbFunctionSetup (uchar data[8])
Definition at line 114 of file SoftUsb.cpp.
References usbRequest::bmRequestType, usbRequest::bRequest, usbWord::bytes, MAGIC_NUMBER, REGISTER_ADDRESS, REGISTER_CHECK, REGISTER_MISSING, REGISTER_OK, REGISTER_READ, REGISTER_WRITE, return_int16(), return_int32(), return_int8(), return_string(), STR, USB_CFG_IOPORTNAME, USB_CONCAT_EXPANDED, USBDRV_VERSION, usbMsgPtr, USBRQ_TYPE_MASK, USBRQ_TYPE_VENDOR, usbRequest::wIndex, usbWord::word, and usbRequest::wValue.
Referenced by SoftUsb::SoftUsb().
{
    //usbMsgLen_t return_value;
    usbRequest_t *rq = (usbRequest_t*) ((void *) data);
    byte cmd = rq->bRequest;
    word wParam = rq->wValue.word;
    byte param1 = rq->wValue.bytes[0];
    byte param2 = rq->wValue.bytes[1];
    byte param3 = rq->wIndex.bytes[0];
    byte param4 = rq->wIndex.bytes[1];
    if ((rq->bmRequestType & USBRQ_TYPE_MASK) == USBRQ_TYPE_VENDOR)
    {
        usbMsgPtr = dataBuffer; /* tell the driver which data to return */
        switch (cmd)
        {
        case 10:
            digitalWrite(param1, param2);
            break;
        case 11:
            pinMode(param1, param2);
            break;
        case 12:
            analogWrite(param1, param2);
            break;
        case 13:
            return return_int8(digitalRead(param1));
            break;
        case 14:
            analogReference(param1);
            break;
        case 22:
            return return_string(__TIME__);
            break;
        case 23:
            return return_string(__DATE__);
            break;
        case 24:
            return return_string(__VERSION__);
            break;
        case 25:
            return return_string(STR(USBDRV_VERSION));
            break;
        case 26:
            return return_string(MCU_DEFINED);
            break;
        case 27:
            return return_int16(analogRead(param1));
            break;
        case 29:
            return return_int8(digitalPinToBitMask(param1));
            break;
        case 30:
            return return_int8(digitalPinToPort(param1));
            break;
        case 31:
            return return_int8(*portModeRegister(param1));
            break;
        case 34:
            return return_int8(USB_CONCAT_EXPANDED(P, USB_CFG_IOPORTNAME));
            break;
//      case 35:
//          return return_int8(A0);
//          break;
        case 36:
            return return_int8(digitalPinToTimer(param1));
            break;
        case 37:
            return return_int8(analogInPinToBit(param1));
            break;
        case 38:
            return return_int8(*portOutputRegister(param1));
            break;
        case 39:
            return return_int8(*portInputRegister(param1));
            break;
        case MAGIC_NUMBER://42
            return return_int8(MAGIC_NUMBER);
            break;
        case 50:
        {
            word w = 0;
            for (unsigned int i = 0; i < sizeof(reg_index_list); i++)
            {
                word index = pgm_read_word(&reg_index_list[i]);
                if (index == wParam)
                {
                    w = pgm_read_word(&reg_list[i]);
                    break;
                }
                if (index > wParam)
                    break;
            }
            if (w == 0)
            {
                // register not found
                switch (param3)
                {
                case REGISTER_CHECK:
                    return return_int8(REGISTER_MISSING);
                    break;
                default:
                    return 0;
                }
            }
            volatile byte* preg = (volatile byte*) w;
            switch (param3)
            {
            case REGISTER_WRITE:
                *preg = param4;
                break;
            case REGISTER_READ:
                return return_int8(*preg);
                break;
            case REGISTER_CHECK:
                return return_int8(REGISTER_OK);
                break;
            case REGISTER_ADDRESS:
                return return_int16((int16_t) preg);
                break;
            }
        }
            break;
        case 51:
        {
            uint32_t w = pgm_read_dword(&intdef_list[param1]);
            return return_int32(w);
        }
            break;
        }
    }
    else
    {
        /* class requests USBRQ_HID_GET_REPORT and USBRQ_HID_SET_REPORT are
         * not implemented since we never call them. The operating system
         * won't call them either because our descriptor defines no meaning.
         */
    }
    return 0; /* default for not implemented requests: return no data back to host */
}
Variable Documentation
const prog_uint32_t intdef_list [] PROGMEM
Definition at line 88 of file SoftUsb.cpp.