softusbduino: SoftUsb/SoftUsb.h File Reference
SoftUsb/SoftUsb.h File Reference
#include "UsbMain.h"
#include <avr/version.h>
#include <avr/wdt.h>
#include <avr/interrupt.h>
#include <util/delay.h>
#include <avr/pgmspace.h>
#include "generated_version.h"
#include "WProgram.h"
#include "pins_arduino.h"
#include "SoftUsb.h"
#include "generated_mcu.h"
#include "generated_registers.h"
#include "generated_intdefs.h"
Classes
struct params
class SoftUsb
Defines
#define MAGIC_NUMBER 42
#define _STR(s) #s
#define STR(s) _STR(s)
#define PA 1
#define PB 2
#define PC 3
#define PD 4
#define PE 5
#define PF 6
#define PG 7
#define PH 8
#define PJ 10
#define PK 11
#define PL 12
#define REGISTER_CHECK 1
#define REGISTER_READ 2
#define REGISTER_WRITE 3
#define REGISTER_ADDRESS 4
#define REGISTER_MISSING 111
#define REGISTER_OK 222
#define BUFFER_SIZE 20
#define TYPE_INT8 1
#define TYPE_INT16 2
#define TYPE_INT32 3
#define TYPE_STRING 4
#define TYPE_FLOAT 5
#define TYPE_VOID 6
#define TYPE_BYTE_ARRAY 7
#define DEFINE(x) (prog_uint16_t)(&x),
#define MISSING(x)
#define DEFINE(x) __COUNTER__,
#define MISSING(x) (0*__COUNTER__)+
#define DEFINE(x) x,
Typedefs
typedef struct params params_t
Functions
usbMsgLen_t return_string (const char *s)
usbMsgLen_t return_byte_array (const byte *arr, int8_t size)
usbMsgLen_t return_int8 (int8_t x)
usbMsgLen_t return_bool (int8_t x)
usbMsgLen_t return_int16 (int16_t x)
usbMsgLen_t return_int32 (int32_t x)
void * operator new (size_t size)
void operator delete (void *ptr)
void delay_test (params_t *p)
usbMsgLen_t SoftUsb_UsbFunctionSetup (uchar data[8])
Variables
const prog_uint16_t reg_list[] PROGMEM
bool run_slow = false
int slow_return
params_t slow_params
Define Documentation
#define _STR (s) #s
Definition at line 23 of file SoftUsb.h.
#define BUFFER_SIZE 20
Definition at line 45 of file SoftUsb.h.
#define DEFINE (x) x,
Definition at line 122 of file SoftUsb.h.
#define DEFINE (x) (prog_uint16_t)(&x),
Definition at line 122 of file SoftUsb.h.
#define DEFINE (x) __COUNTER__,
Definition at line 122 of file SoftUsb.h.
#define MAGIC_NUMBER 42
Definition at line 21 of file SoftUsb.h.
Referenced by SoftUsb_UsbFunctionSetup().
#define MISSING (x) (0*__COUNTER__)+
Definition at line 113 of file SoftUsb.h.
#define MISSING (x)
Definition at line 113 of file SoftUsb.h.
#define PA 1
Definition at line 26 of file SoftUsb.h.
#define PB 2
Definition at line 27 of file SoftUsb.h.
#define PC 3
Definition at line 28 of file SoftUsb.h.
#define PD 4
Definition at line 29 of file SoftUsb.h.
#define PE 5
Definition at line 30 of file SoftUsb.h.
#define PF 6
Definition at line 31 of file SoftUsb.h.
#define PG 7
Definition at line 32 of file SoftUsb.h.
#define PH 8
Definition at line 33 of file SoftUsb.h.
#define PJ 10
Definition at line 34 of file SoftUsb.h.
#define PK 11
Definition at line 35 of file SoftUsb.h.
#define PL 12
Definition at line 36 of file SoftUsb.h.
#define REGISTER_ADDRESS 4
Definition at line 41 of file SoftUsb.h.
Referenced by SoftUsb_UsbFunctionSetup().
#define REGISTER_CHECK 1
Definition at line 38 of file SoftUsb.h.
Referenced by SoftUsb_UsbFunctionSetup().
#define REGISTER_MISSING 111
Definition at line 42 of file SoftUsb.h.
Referenced by SoftUsb_UsbFunctionSetup().
#define REGISTER_OK 222
Definition at line 43 of file SoftUsb.h.
Referenced by SoftUsb_UsbFunctionSetup().
#define REGISTER_READ 2
Definition at line 39 of file SoftUsb.h.
Referenced by SoftUsb_UsbFunctionSetup().
#define REGISTER_WRITE 3
Definition at line 40 of file SoftUsb.h.
Referenced by SoftUsb_UsbFunctionSetup().
#define STR (s) _STR(s)
Definition at line 24 of file SoftUsb.h.
Referenced by SoftUsb_UsbFunctionSetup().
#define TYPE_BYTE_ARRAY 7
Definition at line 53 of file SoftUsb.h.
Referenced by return_byte_array().
#define TYPE_FLOAT 5
Definition at line 51 of file SoftUsb.h.
#define TYPE_INT16 2
Definition at line 48 of file SoftUsb.h.
Referenced by return_int16().
#define TYPE_INT32 3
Definition at line 49 of file SoftUsb.h.
Referenced by return_int32().
#define TYPE_INT8 1
Definition at line 47 of file SoftUsb.h.
Referenced by return_int8().
#define TYPE_STRING 4
Definition at line 50 of file SoftUsb.h.
Referenced by return_string().
#define TYPE_VOID 6
Definition at line 52 of file SoftUsb.h.
Typedef Documentation
typedef struct params params_t
Function Documentation
void delay_test (params_t * p)
Definition at line 161 of file SoftUsb.h.
References params::bytes, and params::word1.
Referenced by SoftUsb::refresh(), and SoftUsb_UsbFunctionSetup().
{
    if (p->bytes[0])
        noInterrupts();
    if (p->bytes[1])
        delay(p->word1);
    else
        delayMicroseconds(p->word1);
    if (p->bytes[0])
        interrupts();
}
void operator delete (void * ptr)
Definition at line 138 of file SoftUsb.h.
{
    free(ptr);
}
void* operator new (size_t size)
Definition at line 133 of file SoftUsb.h.
{
    return malloc(size);
}
usbMsgLen_t return_bool (int8_t x)
Definition at line 80 of file SoftUsb.h.
References return_int8().
Referenced by SoftUsb::refresh().
{
    return return_int8(x);
}
usbMsgLen_t return_byte_array (const byte * arr, int8_t size)
Definition at line 63 of file SoftUsb.h.
References TYPE_BYTE_ARRAY.
Referenced by SoftUsb_UsbFunctionSetup().
{
    dataBuffer[0] = TYPE_BYTE_ARRAY;
    for (int i = 0; i < size; i++)
    {
        dataBuffer[i + 1] = arr[i];
    }
    return size + 1;
}
usbMsgLen_t return_int16 (int16_t x)
Definition at line 85 of file SoftUsb.h.
References TYPE_INT16.
Referenced by SoftUsb_UsbFunctionSetup().
{
    dataBuffer[0] = TYPE_INT16;
    dataBuffer[1] = x >> (0 * 8);
    dataBuffer[2] = x >> (1 * 8);
    return 3;
}
usbMsgLen_t return_int32 (int32_t x)
Definition at line 93 of file SoftUsb.h.
References TYPE_INT32.
Referenced by SoftUsb_UsbFunctionSetup().
{
    dataBuffer[0] = TYPE_INT32;
    dataBuffer[1] = x >> (0 * 8);
    dataBuffer[2] = x >> (1 * 8);
    dataBuffer[3] = x >> (2 * 8);
    dataBuffer[4] = x >> (3 * 8);
    return 5;
}
usbMsgLen_t return_int8 (int8_t x)
Definition at line 73 of file SoftUsb.h.
References TYPE_INT8.
Referenced by SoftUsb::refresh(), return_bool(), and SoftUsb_UsbFunctionSetup().
{
    dataBuffer[0] = TYPE_INT8;
    dataBuffer[1] = x;
    return 2;
}
usbMsgLen_t return_string (const char * s)
Definition at line 56 of file SoftUsb.h.
References TYPE_STRING.
Referenced by SoftUsb_UsbFunctionSetup().
{
    dataBuffer[0] = TYPE_STRING;
    strcpy((char*) &dataBuffer[1], s);
    return strlen((char*) dataBuffer) + 1;
}
usbMsgLen_t SoftUsb_UsbFunctionSetup (uchar data[8])
Definition at line 175 of file SoftUsb.h.
References usbRequest::bmRequestType, usbRequest::bRequest, usbWord::bytes, params::bytes, params::cmd, delay_test(), MAGIC_NUMBER, REGISTER_ADDRESS, REGISTER_CHECK, REGISTER_MISSING, REGISTER_OK, REGISTER_READ, REGISTER_WRITE, return_byte_array(), return_int16(), return_int32(), return_int8(), return_string(), run_slow, slow_return, STR, USB_CFG_IOPORTNAME, USB_CONCAT_EXPANDED, USBDRV_VERSION, usbMsgPtr, USBRQ_TYPE_MASK, USBRQ_TYPE_VENDOR, usbRequest::wIndex, usbWord::word, params::word1, and usbRequest::wValue.
Referenced by SoftUsb::SoftUsb().
{
    usbRequest_t *rq = (usbRequest_t*) ((void *) data);
    byte cmd = rq->bRequest;
    params_t params;
    params.cmd = rq->bRequest;
    params.bytes[0] = rq->wValue.bytes[0];
    params.bytes[1] = rq->wValue.bytes[1];
    params.bytes[2] = rq->wIndex.bytes[0];
    params.bytes[3] = rq->wIndex.bytes[1];
    params.word1 = rq->wIndex.word; // same as (params.bytes[2];params.bytes[3])
    if ((rq->bmRequestType & USBRQ_TYPE_MASK) == USBRQ_TYPE_VENDOR)
    {
        usbMsgPtr = dataBuffer; /* tell the driver which data to return */
        switch (cmd)
        {
        case 10:
            digitalWrite(params.bytes[0], params.bytes[1]);
            break;
        case 11:
            pinMode(params.bytes[0], params.bytes[1]);
            break;
        case 12:
            analogWrite(params.bytes[0], params.bytes[1]);
            break;
        case 13:
            return return_int8(digitalRead(params.bytes[0]));
            break;
        case 14:
            analogReference(params.bytes[0]);
            break;
        case 22:
            return return_string(__TIME__);
            break;
        case 23:
            return return_string(__DATE__);
            break;
        case 24:
            return return_string(__VERSION__);
            break;
        case 25:
            return return_string(STR(USBDRV_VERSION));
            break;
        case 26:
            return return_string(MCU_DEFINED);
            break;
        case 27:
            return return_int16(analogRead(params.bytes[0]));
            break;
        case 29:
            return return_int8(digitalPinToBitMask(params.bytes[0]));
            break;
        case 30:
            return return_int8(digitalPinToPort(params.bytes[0]));
            break;
        case 31:
            return return_int8(*portModeRegister(params.bytes[0]));
            break;
        case 34:
            return return_int8(USB_CONCAT_EXPANDED(P, USB_CFG_IOPORTNAME));
            break;
        case 36:
            return return_int8(digitalPinToTimer(params.bytes[0]));
            break;
        case 37:
            return return_int8(analogInPinToBit(params.bytes[0]));
            break;
        case 38:
            return return_int8(*portOutputRegister(params.bytes[0]));
            break;
        case 39:
            return return_int8(*portInputRegister(params.bytes[0]));
            break;
        case MAGIC_NUMBER://42
            return return_int8(MAGIC_NUMBER);
            break;
        case 50:
        {
            word w = 0;
            for (unsigned int i = 0; i < sizeof(reg_index_list); i++)
            {
                word index = pgm_read_word(&reg_index_list[i]);
                if (index == params.word1)
                {
                    w = pgm_read_word(&reg_list[i]);
                    break;
                }
                if (index > params.word1)
                    break;
            }
            if (w == 0)
            {
                // register not found
                switch (params.bytes[0])
                {
                case REGISTER_CHECK:
                    return return_int8(REGISTER_MISSING);
                    break;
                default:
                    return 0;
                }
            }
            volatile byte* preg = (volatile byte*) w;
            switch (params.bytes[0])
            {
            case REGISTER_WRITE:
                *preg = params.bytes[1];
                break;
            case REGISTER_READ:
                return return_int8(*preg);
                break;
            case REGISTER_CHECK:
                return return_int8(REGISTER_OK);
                break;
            case REGISTER_ADDRESS:
                return return_int16((int16_t) preg);
                break;
            }
        }
            break;
        case 51:
        {
            uint32_t w = pgm_read_dword(&intdef_list[params.bytes[0]]);
            return return_int32(w);
        }
            break;
#ifdef OneWire_h
        case 62:
            if (one_wire_bus_list[params.bytes[0]])
            {
                delete one_wire_bus_list[params.bytes[0]];
            }
            one_wire_bus_list[params.bytes[0]] = new OneWire(params.bytes[1]);
            break;
        case 64:
            one_wire_bus_list[params.bytes[0]]->reset_search();
            break;
        case 65:
            slow_params = params;
            run_slow = true;
            break;
        case 66:
            slow_params = params;
            run_slow = true;
            break;
        case 67:
            slow_params = params;
            run_slow = true;
            break;
        case 68:
            slow_params = params;
            run_slow = true;
            break;
        case 69:
            one_wire_bus_list[params.bytes[0]]->depower();
            break;
        case 70:
            return return_byte_array(one_wire_address, 8);
            break;
        case 71:
            one_wire_address[0] = params.bytes[0];
            one_wire_address[1] = params.bytes[1];
            one_wire_address[2] = params.bytes[2];
            one_wire_address[3] = params.bytes[3];
            break;
        case 72:
            one_wire_address[4] = params.bytes[0];
            one_wire_address[5] = params.bytes[1];
            one_wire_address[6] = params.bytes[2];
            one_wire_address[7] = params.bytes[3];
            break;
        case 73:
            slow_params = params;
            run_slow = true;
            break;
#endif
        case 200:
        {
            return slow_return;
            break;
        }
        case 210:
        {
            delay_test(&params);
            break;
        }
        case 211:
            slow_params = params;
            run_slow = true;
            break;
        }
    }
    else
    {
        /* class requests USBRQ_HID_GET_REPORT and USBRQ_HID_SET_REPORT are
         * not implemented since we never call them. The operating system
         * won't call them either because our descriptor defines no meaning.
         */
    }
    return 0; /* default for not implemented requests: return no data back to host */
}
Variable Documentation
const prog_uint32_t intdef_list [] PROGMEM
Definition at line 105 of file SoftUsb.h.
bool run_slow = false
Definition at line 149 of file SoftUsb.h.
Referenced by SoftUsb::refresh(), and SoftUsb_UsbFunctionSetup().
params_t slow_params
Definition at line 159 of file SoftUsb.h.
int slow_return
Definition at line 150 of file SoftUsb.h.
Referenced by SoftUsb::refresh(), and SoftUsb_UsbFunctionSetup().