softusbduino: SoftUsb/SoftUsb_return.h File Reference
SoftUsb_return.h File Reference
Macros
#define BUFFER_SIZE 20
#define TYPE_INT8 1
#define TYPE_INT16 2
#define TYPE_INT32 3
#define TYPE_STRING 4
#define TYPE_FLOAT 5
#define TYPE_VOID 6
#define TYPE_BYTE_ARRAY 7
Functions
usbMsgLen_t return_string (const char *s)
usbMsgLen_t return_byte_array (const byte *arr, int8_t size)
usbMsgLen_t return_int8 (int8_t x)
usbMsgLen_t return_bool (int8_t x)
usbMsgLen_t return_int16 (int16_t x)
usbMsgLen_t return_int32 (int32_t x)
Macro Definition Documentation
#define BUFFER_SIZE 20
Definition at line 3 of file SoftUsb_return.h.
#define TYPE_BYTE_ARRAY 7
Definition at line 11 of file SoftUsb_return.h.
Referenced by return_byte_array().
#define TYPE_FLOAT 5
Definition at line 9 of file SoftUsb_return.h.
#define TYPE_INT16 2
Definition at line 6 of file SoftUsb_return.h.
Referenced by return_int16().
#define TYPE_INT32 3
Definition at line 7 of file SoftUsb_return.h.
Referenced by return_int32().
#define TYPE_INT8 1
Definition at line 5 of file SoftUsb_return.h.
Referenced by return_int8().
#define TYPE_STRING 4
Definition at line 8 of file SoftUsb_return.h.
Referenced by return_string().
#define TYPE_VOID 6
Definition at line 10 of file SoftUsb_return.h.
Function Documentation
usbMsgLen_t return_bool (int8_t x)
Definition at line 38 of file SoftUsb_return.h.
References return_int8().
Referenced by SoftUsb::refresh().
{
    return return_int8(x);
}
usbMsgLen_t return_byte_array (const byte * arr, int8_t size)
Definition at line 21 of file SoftUsb_return.h.
References TYPE_BYTE_ARRAY.
Referenced by SoftUsb_UsbFunctionSetup().
{
    dataBuffer[0] = TYPE_BYTE_ARRAY;
    for (int i = 0; i < size; i++)
    {
        dataBuffer[i + 1] = arr[i];
    }
    return size + 1;
}
usbMsgLen_t return_int16 (int16_t x)
Definition at line 43 of file SoftUsb_return.h.
References TYPE_INT16.
Referenced by SoftUsb_UsbFunctionSetup().
{
    dataBuffer[0] = TYPE_INT16;
    dataBuffer[1] = x >> (0 * 8);
    dataBuffer[2] = x >> (1 * 8);
    return 3;
}
usbMsgLen_t return_int32 (int32_t x)
Definition at line 51 of file SoftUsb_return.h.
References TYPE_INT32.
Referenced by SoftUsb_UsbFunctionSetup().
{
    dataBuffer[0] = TYPE_INT32;
    dataBuffer[1] = x >> (0 * 8);
    dataBuffer[2] = x >> (1 * 8);
    dataBuffer[3] = x >> (2 * 8);
    dataBuffer[4] = x >> (3 * 8);
    return 5;
}
usbMsgLen_t return_int8 (int8_t x)
Definition at line 31 of file SoftUsb_return.h.
References TYPE_INT8.
Referenced by SoftUsb::refresh(), return_bool(), and SoftUsb_UsbFunctionSetup().
{
    dataBuffer[0] = TYPE_INT8;
    dataBuffer[1] = x;
    return 2;
}
usbMsgLen_t return_string (const char * s)
Definition at line 14 of file SoftUsb_return.h.
References TYPE_STRING.
Referenced by SoftUsb_UsbFunctionSetup().
{
    dataBuffer[0] = TYPE_STRING;
    strcpy((char*) &dataBuffer[1], s);
    return strlen((char*) dataBuffer) + 1;
}